### PR TITLE
update who's on call test to match current code.

### PR DESCRIPTION
**Pull request by aaronblythe**
Update to get current tests to all pass.

### CODE REVIEW

**Comment by stephenyeargin** [comment]
:+1: We should really get this wired into CI, even for the small stuff like responders.

**Comment by aaronblythe** [comment]
+1 Are you thinking Travis.CI?

**Comment by stephenyeargin** [comment]
Hm. Apparently I can enable it after all. I think somebody at GitHub gave me too much permission on this repository. :grinning:

**Comment by stephenyeargin** [comment]
Fixed in `v2.1.9`

**Comment by stephenyeargin** [comment]
Wired up for future PRs.

screen shot 2015-11-16 at 4 12 06 pm

**Pull request merged**
