### PR TITLE
ignores the ?

### PR DESCRIPTION
**Pull request by d4v3y0rk**
fix for hubot-scripts/hubot-pager-me#47
the regex comes from @danoc
cc @stephenyeargin

### CODE REVIEW

**Comment by stephenyeargin** [comment]
Adding the non-capturing flag `?:` should change the index here, shouldn't it?

https://github.com/hubot-scripts/hubot-pager-me/pull/73/files#diff-b6367b6561a9b2675121a45cd273efceR559

**Comment by d4v3y0rk** [comment]
you are correct sir, fix submitted. 
cc @stephenyeargin 
match aray

**Comment by stephenyeargin** [comment]
:+1:

**Comment by stephenyeargin** [comment]
Released as part of `v2.1.12`

**Pull request merged**
