### PR TITLE
Fix command documentation to be in the proper format.

### PR DESCRIPTION
**Pull request by stevemostovoy**
The current implementation causes the help message to be near unreadable.

### CODE REVIEW

**Comment by stevemostovoy** [comment]
@stephenyeargin

**Comment by stephenyeargin** [comment]
:+1: Good with it.

**Comment by stevemostovoy** [comment]
@stephenyeargin Thanks, can we merge?

**Comment by stephenyeargin** [comment]
Yeah, I'll give it a spin. I'm usually not eager to run point on releases for this package, as I know :octocat: use(s|d) it heavily with their internal tooling. /cc @jnewland @technicalpickles

**Comment by stephenyeargin** [comment]
`v2.1.4` shipped.

**Comment by stevemostovoy** [comment]
Thanks!

**Pull request merged**
